// this file is autogenerated from the wheels described in ../package.json
export const allJSONUrl = { default: '' };
export const ipykernelWheelUrl = { default: undefined };
export const pipliteWheelUrl = { default: '' };
export const pyodide_kernelWheelUrl = { default: undefined };
export const widgetsnbextensionWheelUrl = { default: undefined };
export const widgetsnbextensionWheelUrl1 = { default: undefined };
