import type { CancellationToken } from 'vscode'
import { ResponsesStreamError } from './openai/openaiResponsesApi.js'


/**
 * Prefix of the retry marker emitted when a request fails with a retryable
 * error; the suffix is a unique HTML comment. The Stop hook
 * (able-empty-retry.mjs) detects the marker at the end of the latest assistant
 * message in the transcript and asks the model to continue, mirroring the
 * empty-response marker emitted by CommonApi.emitFallbackResponseIfNeeded.
 * The marker ends with an HTML comment, which is stripped from the chat view
 * by the sanitizer but preserved in the transcript; the random hex suffix
 * makes every marker unique.
 */
export const RETRYABLE_ERROR_MARKER_PREFIX = '\nThis is a marker indicating that the request failed with a retryable error, generated by VS Code Chat Plugin:\n'

/**
 * Whether a request error should be retried through the Stop hook instead of
 * being surfaced to the user. Retryable: interrupted tool-call streams,
 * missing tool call ids, network failures, connect-phase and stream timeouts,
 * transient failures reported through stream events (rate_limit_exceeded,
 * server_error), and HTTP statuses that may succeed on retry (408, 425, 429,
 * 5xx). Non-retryable: user cancellation and client errors (400, 401, 403,
 * ...), which cannot succeed on retry.
 */
export function isRetryableError(error: unknown, httpTimedOut: boolean, token: CancellationToken): boolean {
    if (token.isCancellationRequested) {
        return false
    }
    if (httpTimedOut) {
        return true
    }
    if (error instanceof ResponsesStreamError) {
        // Stream timeouts and streams ending before a terminal event are
        // transient gateway failures; a fresh request may succeed.
        return true
    }
    if (error instanceof Error) {
        if (error.name === 'AbortError') {
            // User cancellation aborts the same controller; never retry it.
            return false
        }
        const message = error.message
        if (
            message.includes('Stream ended with incomplete tool calls') ||
            message.includes('Tool call missing id') ||
            message.includes('fetch failed') ||
            // Event-based transient failures (see openaiResponsesApi):
            // error events and response.failed carry provider codes such as
            // rate_limit_exceeded and server_error in the message.
            message.includes('rate_limit_exceeded') ||
            message.includes('server_error')
        ) {
            return true
        }
        // HTTP error messages embed the status code as [NNN] (see
        // CommonApi.postAndGetBody). 408/425/429/5xx may succeed on retry;
        // other status codes are client errors that cannot.
        const statusMatch = message.match(/\[(\d{3})\]/)
        if (statusMatch) {
            const status = Number(statusMatch[1])
            return status === 408 || status === 425 || status === 429 || status >= 500
        }
    }
    return false
}
