import { strict as assert } from 'node:assert'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { suite, setup, teardown, test } from 'mocha'
import { GOAL_COMPLETE_MARKER, makeGoalMarker } from '../../../src/chatprovider/opencodegochatprovider/goal.js'

// The compiled test lives at out/test/unittest/chatprovider/, so four levels
// up is the repository root. The test output is CommonJS, so __dirname works.
const hookPath = path.join(__dirname, '..', '..', '..', '..', 'scripts', 'ablegoalcontinue.mjs')

interface HookOutput {
    readonly hookSpecificOutput?: {
        readonly hookEventName?: string
        readonly decision?: string
        readonly reason?: string
    }
}

suite('ablegoalcontinue hook', () => {
    let tempDir: string

    setup(() => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ablegoalcontinue-'))
    })

    teardown(() => {
        fs.rmSync(tempDir, { recursive: true, force: true })
    })

    function writeTranscript(lines: readonly unknown[]): string {
        const transcriptPath = path.join(tempDir, 'transcript.jsonl')
        fs.writeFileSync(transcriptPath, `${lines.map(line => JSON.stringify(line)).join('\n')}\n`)
        return transcriptPath
    }

    function runHook(transcriptPath: string): string {
        return execFileSync(process.execPath, [hookPath], {
            input: JSON.stringify({ session_id: 'test-session', cwd: tempDir, transcript_path: transcriptPath }),
            encoding: 'utf8',
        })
    }

    function parseHookOutput(output: string): HookOutput {
        return JSON.parse(output) as HookOutput
    }

    test('blocks the stop while a goal is active', () => {
        const transcriptPath = writeTranscript([
            { type: 'user.message', data: { content: '/goal fix the login bug' } },
            { type: 'assistant.message', data: { content: `Goal set.\n\n${makeGoalMarker('set', 'fix the login bug')}` } },
        ])
        const parsed = parseHookOutput(runHook(transcriptPath))
        assert.strictEqual(parsed.hookSpecificOutput?.hookEventName, 'Stop')
        assert.strictEqual(parsed.hookSpecificOutput?.decision, 'block')
        assert.ok(parsed.hookSpecificOutput?.reason?.includes('fix the login bug'))
    })

    test('exits without output when no goal is set', () => {
        const transcriptPath = writeTranscript([
            { type: 'user.message', data: { content: 'hello' } },
            { type: 'assistant.message', data: { content: 'Hi there.' } },
        ])
        assert.strictEqual(runHook(transcriptPath), '')
    })

    test('exits without output when the goal is complete', () => {
        const transcriptPath = writeTranscript([
            { type: 'assistant.message', data: { content: `Goal set.\n\n${makeGoalMarker('set', 'fix the login bug')}` } },
            { type: 'user.message', data: { content: 'Please continue and complete the active goal.' } },
            { type: 'assistant.message', data: { content: `All requirements verified.\n${GOAL_COMPLETE_MARKER}` } },
        ])
        assert.strictEqual(runHook(transcriptPath), '')
    })

    test('exits without output when the goal is paused', () => {
        const transcriptPath = writeTranscript([
            { type: 'assistant.message', data: { content: `Goal set.\n\n${makeGoalMarker('set', 'fix the login bug')}` } },
            { type: 'assistant.message', data: { content: makeGoalMarker('paused') } },
        ])
        assert.strictEqual(runHook(transcriptPath), '')
    })

    test('exits without output when the turn budget is exhausted', () => {
        const entries: unknown[] = [
            { type: 'assistant.message', data: { content: `Goal set.\n\n${makeGoalMarker('set', 'fix the login bug')}` } },
        ]
        for (let index = 0; index < 20; index++) {
            entries.push({ type: 'user.message', data: { content: 'Please continue and complete the active goal.' } })
            entries.push({ type: 'assistant.message', data: { content: `Progress on turn ${index + 1}.` } })
        }
        const transcriptPath = writeTranscript(entries)
        assert.strictEqual(runHook(transcriptPath), '')
    })

    test('exits without output when the latest assistant message ends with a retry marker', () => {
        const transcriptPath = writeTranscript([
            { type: 'assistant.message', data: { content: `Goal set.\n\n${makeGoalMarker('set', 'fix the login bug')}` } },
            {
                type: 'assistant.message',
                data: {
                    content: 'This is a marker indicating that the request failed with a retryable error, generated by VS Code Chat Plugin:\n<!-- ABLE_RETRYABLE_ERROR_0123abcd -->',
                },
            },
        ])
        assert.strictEqual(runHook(transcriptPath), '')
    })
})
